### ISSUE TITLE
TokenFallback  Function Clarification

### ISSUE THREAD

**Issue by mariam-crissi** [Dexaran/ERC223-token-standard#20]
I am trying to create an ICO based on ERC223.

In my Token Creation Contract.I have defined an interface for CrowdSale with tokenFallback Function.

       interface CrowdSale {
                  function tokenFallback(address _from, uint _value, bytes _data);
       }

And also I have written the transfer function with respect to ERC223 syntax.

    function transfer(address _to, uint _value) {
    uint codeLength;
    bytes memory empty;
    assembly {
        // Retrieve the size of the code on target address, this needs assembly .
        codeLength := extcodesize(_to)
    }
    //Cheking Conditions
    require(balanceOf[msg.sender] > 0);
	require(balanceOf[msg.sender] >= _value);
	require(balanceOf[_to] + _value >= balanceOf[_to]);
    //Transfer Execution
    balanceOf[msg.sender] -= _value;
    balanceOf[_to] += _value;
    //If _to is a contract Address
    if (codeLength>0) {
        CrowdSale receiver = CrowdSale(_to);
        receiver.tokenFallback(msg.sender, _value, empty);
    }
    //Event Emitting
    Transfer(msg.sender, _to, _value, empty);
}

Then I created CrowdSale Contract
Here I have defined to emit an event.

               function tokenFallback(address from,uint value,bytes data) public {
                                        LOGTokenFallBack(from,value,data);
                                       //****************** */
                                       //Testing Transfer of Coins
                                      tokenReward.transfer(from,value);
                                      //****************** */
                  }

I can change the ownership of token as crowdsale contract..But I can't able to transfer tokens into crowdsale contract.How can I execute this?

Can you please help me?

**Comment by Dexaran** [comment]
@mariam-crissi I don't know who is `tokenReward` address. May be it implements the `transfer` function that you are trying to call, may be not. You didn't explained what is the `tokenReward`. 

Also, I see that you are trying to call transfer method at the `tokenReward` address but I don't know the purpose of this call. 

You should keep in mind that the transfer of tokens is **already done** at the time of execution of `tokenFallback` function.  It seems that `tokenReward` is another token contract that implements its own `transfer` function and you are trying to transfer "Token Reward tokens" on each incoming ERC223 token transaction.
