### ISSUE TITLE
Possible we should add truffle and unit testing for this token?

### ISSUE THREAD

**Issue by DeRain** [Dexaran/ERC223-token-standard#23]

**Comment by Dexaran** [comment]
This is an example of the implementation of the standard ERC223. The token standard is a description of the functions of the token, signatures, and their logic. I don't see any reason to clutter the repository of example token with codes that are not related to the token standard at all.

I prefer to keep the repository free from any codes that are not directly related to token standard. We can create a set of example tokens with necessary tests and put them in separate repo.

**Comment by DeRain** [comment]
Agree. I think it could be separate repo or we could include base token
implementation in the OpenZeppelin repository.

**Comment by JackPickering** [comment]
Did you create this repo?

**Comment by DeRain** [comment]
No actually I did have a chance. Feel feee to create the repo and I will be
glad to provide a truffle based implementation of the token.
