### ISSUE TITLE
Balance checks in ERC223_token.sol

### ISSUE THREAD

**Issue by TovarishFin** [Dexaran/ERC223-token-standard#45]
Are the balance checks in the various transfer functions actually needed? Shouldn't the safe math functions catch these issues?

**Comment by Dexaran** [comment]
As you can see there are no balance checks currently https://github.com/Dexaran/ERC223-token-standard/blob/master/token/ERC223/ERC223_token.sol#L36-L37

**Comment by TovarishFin** [comment]
Sorry must have been looking at a different version.
