### ISSUE TITLE
Transfer event doesn't log custom fallback if used.

### ISSUE THREAD

**Issue by ARitz-Cracker** [Dexaran/ERC223-token-standard#48]
So I see that a custom fallback is specified in the interface. That's pretty cool.
However, if you're logging data, shouldn't you also be logging which function was used as well? Why is data being logged anyway since anyone looking for that kind of information would look it up from the transaction?

**Comment by ARitz-Cracker** [comment]
I looked through the repo again and I noticed that custom fallbacks are no longer a thing. Have you decided against this?

**Comment by Dexaran** [comment]
custom fallbacks were moved to the "Recommender" branch. I do not think that we need to introduce a separate event signature (Transfer with custom function name) for logging the function name. Anyways, it is still possible to recognize the function name from tx.data. As the result, it is decided that introducing separate Transfer event for custom fallbacks is not worth it.
