### ISSUE TITLE
ERC223 interface and implementation not fully compatible with EIP20

### ISSUE THREAD

**Issue by 0rand** [Dexaran/ERC223-token-standard#49]
The proposed interface declares only Transfer event which is not compatible with ERC20 event:
` event Transfer(address indexed from, address indexed to, uint value, bytes indexed data);`
versus event in EIP20:
`event Transfer(address indexed from, address indexed to, uint value);`

Also the implementation causes emiting EIP20-not compatible events when using EIP20 backward-compatible function Transfer:
`function transfer(address to, uint value) public returns (bool ok);`

As a result EIP20-compatible dApps won't recognize the Transfer event fired by the token contract since it has a different signature due to different set of topics:

Backward-compatible Transfer function calls an internal method:
 ```
function transfer(address _to, uint _value) public returns (bool success) {
   //standard function transfer similar to ERC20 transfer with no _data
    //added due to backwards compatibility reasons
    bytes memory empty;
    if(isContract(_to)) {
        return transferToContract(_to, _value, empty);
    }
    else {
        return transferToAddress(_to, _value, empty);
    }
```
which in the end fires non-compatible event:
```
function transferToAddress(address _to, uint _value, bytes _data) private returns (bool success) {
    if (balanceOf(msg.sender) < _value) revert();
    balances[msg.sender] = safeSub(balanceOf(msg.sender), _value);
    balances[_to] = safeAdd(balanceOf(_to), _value);
    // =======================
     emit Transfer(msg.sender, _to, _value, _data);
    // =======================    
    return true;
  }
```
and
```
function transferToContract(address _to, uint _value, bytes _data) private returns (bool success) {
    if (balanceOf(msg.sender) < _value) revert();
    balances[msg.sender] = safeSub(balanceOf(msg.sender), _value);
    balances[_to] = safeAdd(balanceOf(_to), _value);
    ContractReceiver receiver = ContractReceiver(_to);
    receiver.tokenFallback(msg.sender, _value, _data);
       // =============================
    emit Transfer(msg.sender, _to, _value, _data);
   // =============================
    return true;
}

```
I propose a following fix in the interface by adding another Transfer event that is compatible with EIP20:
```
contract ERC223_protofixed {
  uint public totalSupply;
  function balanceOf(address who) public view returns (uint);
  
  function name() public view returns (string _name);
  function symbol() public view returns (string _symbol);
  function decimals() public view returns (uint8 _decimals);
  function totalSupply() public view returns (uint256 _supply);

  function transfer(address to, uint value) public returns (bool ok);
  function transfer(address to, uint value, bytes data) public returns (bool ok);
  function transfer(address to, uint value, bytes data, string custom_fallback) public returns (bool ok);
  
  event Transfer(address indexed from, address indexed to, uint value, bytes indexed data);
  // added event compatible with EIP20 standard
  event Transfer(address indexed from, address indexed to, uint value);
  
}
```

And adding handling of the data into implementation of internal transfer functions:
```
function transferToAddress(address _to, uint _value, bytes _data) private returns (bool success) {
    if (balanceOf(msg.sender) < _value) revert();
    balances[msg.sender] = safeSub(balanceOf(msg.sender), _value);
    balances[_to] = safeAdd(balanceOf(_to), _value);
    
    // updated event emitter to comform EIP20 standard when no data is sent
    if(_data.length == 0) emit Transfer(msg.sender, _to, _value); 
    else emit Transfer(msg.sender, _to, _value, _data);
    
    return true;
  }
  
  //function that is called when transaction target is a contract
  function transferToContract(address _to, uint _value, bytes _data) private returns (bool success) {
    if (balanceOf(msg.sender) < _value) revert();
    balances[msg.sender] = safeSub(balanceOf(msg.sender), _value);
    balances[_to] = safeAdd(balanceOf(_to), _value);
    ContractReceiver receiver = ContractReceiver(_to);
    receiver.tokenFallback(msg.sender, _value, _data);
   
    // updated event emitter to comform EIP20 standard when no data is sent
    if(_data.length == 0) emit Transfer(msg.sender, _to, _value); 
    else emit Transfer(msg.sender, _to, _value, _data);
   
    return true;
}
```

I can do a formal pull request if that is something you want to address. We have hit this issue when integrating ERC223 token handling implementation in our wallet and backend for merchants while working on our project's platform.

**Comment by aleybovich** [comment]
I would improve it further, combining the two functions - they share 90% of the code, the only difference being whether you calla fallback function or not, which you can add a check for right in the function. This way you only have one function instead of two.

And more over, the code for transfer with 2 params (standard ERC20) and code for transfer with 3 params (ERC223) also share most of the code and also should be refactored into two calls into one internal function.

**Comment by Dexaran** [comment]
While I like your idea, I'm not sure if it should be a part of the standard.

In general, the token standard is only a description of the functions specific to this type of tokens, and not all the functions that the developer can implement in it.

**Comment by r3dh4r7** [comment]
So basically if the ERC-20 `Transfer` event signature is added to the ERC-223 interface...
1. A contract can emit either of the proposed `Transfer` events.
2. We'd have to watch for two `Transfer` events when parsing logs.

Wouldn't a contract be capable of confusing a dApp by simply emitting two events with different signatures for a single transfer?
If the answer is yes, then the standard should only contain `Transfer(address,address,uint,bytes)` to prevent abuse.

**Comment by Dexaran** [comment]
>Wouldn't a contract be capable of confusing a dApp by simply emitting two events with different signatures for a single transfer?

The contract can not confuse a DAPP by emitting two types of events.

**Comment by r3dh4r7** [comment]
> The contract can not confuse a DAPP by emitting two types of events.

Pardon me if the reason is obvious, but could you explain?

**Comment by Dexaran** [comment]
@r3dh4r7 

DAPP or [Decentralized Application](https://blockchainhub.net/decentralized-applications-dapps/) is represented by two components: a smart-contract (back-end) and an interface (front-end UI).

The logic of the DAPP is implemented in smart-contract. So, the token will interact with most DAPPs in the same way as smart-contracts interact with each other.  You can read more about interaction between smart-contracts [here](https://zupzup.org/smart-contract-interaction/).

[Events](https://ethereum.stackexchange.com/questions/11228/what-is-an-event) are only relevant to the UI. Events are simply analogues of logs in blockchain and the main purpose of events is to make search in blockchain easier. 

Smart-contracts (which are cores of most DAPPs) are not interacting with events anyhow. Smart-contracts can not read events from blockchain. For recipient of a token transaction it doesn't matter which event was emitted.

**Comment by Dexaran** [comment]
Correct me if I'm wrong or if I'm missing something.

**Comment by Dexaran** [comment]
The logging issue is solved: https://github.com/Dexaran/ERC223-token-standard/commit/73fd6b2925fe7af93a87ca8bda3cb995a4c2a04a

https://github.com/Dexaran/ERC223-token-standard/commit/fd1c3df7a1b6c9653dc8b86e4758a566a56f0371

https://github.com/Dexaran/ERC223-token-standard/commit/84abaf61c0ecb1976372d2bffbdf5d86731ee98e
