### ISSUE TITLE
Bug: low-level calls have problems of transmitting bytes variables

### ISSUE THREAD

**Issue by stevenlcf** [Dexaran/ERC223-token-standard#51]
ERC223 Recommended branch uses low-level calls in its `function transfer(address _to, uint _value, bytes _data, string _custom_fallback) public returns (bool success)` as shown below:
https://github.com/Dexaran/ERC223-token-standard/blob/16d350ec85d5b14b9dc857468c8e0eb4a10572d3/ERC223_Token.sol#L70

However, low-level calls have problems of transmitting bytes variables as a bug of solidity which was discussed in https://github.com/ethereum/solidity/issues/2884#issuecomment-329169020 , where the author of solidity suggested:
> The thing is: `a.call()` is an ancient beast that should not be used. I would recommend using inline assembly for such tasks, since it provides the same security guarantees but does not do any invisible magic.

I also did an experiment with this issue using following codes with the same solidity version `^0.4.9` of ERC223 Recommended branch:

    pragma solidity ^0.4.9;
    
    contract A {
        
        event Receive(
            bytes data
        );
        
        event Send(
            bytes data
        );
        
        function ReceiveCall(bytes data) public {
            emit Receive(data);
        }
        
        function Test() public {
            assert(address(this).call(bytes4(keccak256('ReceiveCall(bytes)')), msg.data));
            emit Send(msg.data);
        }
    }

I ran it in remix and obtained the logs as follow:

	{
		"from": "0x0dcd2f752394c41875e259e00bb44fd505297caf",
		"topic": "0xd30e70c5a77cbe0255cbe85d9cc0d1c4f2229a54affff1dc4b7be37fedcf2dc3",
		"event": "Receive",
		"args": {
			"0": "0x",
			"data": "0x",
			"length": 1
		}
	},
	{
		"from": "0x0dcd2f752394c41875e259e00bb44fd505297caf",
		"topic": "0xd22a6a859e8976f953f5132eca6f648fbff9dbdb61103251027980bd2bd5db4a",
		"event": "Send",
		"args": {
			"0": "0xa163a624",
			"data": "0xa163a624",
			"length": 1
		}
	}

As you can see, the Send's data is `"0xa163a624"` but the Receive's data is `"0x"`.

**Comment by blargity** [comment]
It's actually worse than just not transmitting the data, it corrupts the amount variable, which effectively breaks the `tokenFallback` function pretty much entirely:
ethereum/solidity#4652
https://github.com/blargity/solidity-call-reproduction-case

If the answer on ethereum/solidity#4652 is to use assembly, then I'll figure out the syntax and PR it back here.

**Comment by blargity** [comment]
The syntax of the `.call` should be:

```
assert(address(this).call(abi.encodeWithSignature('ReceiveCall(bytes)', msg.data)));
```

**Comment by jeichel-miovision** [comment]
I've also tested and confirmed, @thekevinbrown, with the following change to `ERC223Token.transfer` for `solidity 0.4.24`
```
  // Function that is called when a user or another contract wants to transfer funds .
  function transfer(address _to, uint _value, bytes _data, string _custom_fallback) public returns (bool success) {

    if(isContract(_to)) {
        if (balanceOf(msg.sender) < _value) revert();
        balances[msg.sender] = safeSub(balanceOf(msg.sender), _value);
        balances[_to] = safeAdd(balanceOf(_to), _value);
        assert(_to.call.value(0)(abi.encodeWithSignature(_custom_fallback, msg.sender, _value, _data)));
        emit Transfer(msg.sender, _to, _value, _data);
        return true;
    }
    else {
        return transferToAddress(_to, _value, _data);
    }
}
```

called from web3
```
await tokenContract.methods.transfer(
        receiverAddress,
        tokenAmount,
        customData,
        'tokenFallback(address,uint256,bytes)',
      ).send({ from: account });
```

**Comment by jeichel-miovision** [comment]
I've tried using both
```
assert(_to.call.value(0)(abi.encodeWithSignature(_custom_fallback, msg.sender, _value, _data)));
```
and
```
assert(_to.call.value(0)(abi.encodeWithSignature(_custom_fallback, abi.encodePacked(msg.sender, _value, _data))));
```

with web3
```
 tokenContract.methods.transfer(receiverAddress, tokenAmount, customData, 'tokenFallback(address,uint256,bytes)').send({ from: account });
```

and while I'm sure my custom contract is being called (via event logging), the `bytes _data` parameter in `function tokenFallback(address _from, uint256 _value, bytes _data) public` is still empty, `0x`.

**Comment by jeichel-miovision** [comment]
I've created several unit tests, as well as an npm project to package the contract and the function call, `assert(_to.call.value(0)(abi.encodeWithSignature(_custom_fallback, msg.sender, _value, _data)));`  seems to work and all of the existing tests.

Have a look at the [fork](https://github.com/open-city-protocol/ERC223-token-standard/tree/1.0.0-rc.7) if interested.

In my previous test, I suspect I did not test sufficient gas when calling the function from `web3`, which resulted in an `invalid opcode` rather than `insufficient gas` error that I was more used to. I don't work with many low-level function calls, so this is probably related to the `assert(...call...)` running out of gas. Either way, I am now able to call customTokenFallback functions.

> I've tried using both
> 
> ```
> assert(_to.call.value(0)(abi.encodeWithSignature(_custom_fallback, msg.sender, _value, _data)));
> ```
> and
> 
> ```
> assert(_to.call.value(0)(abi.encodeWithSignature(_custom_fallback, abi.encodePacked(msg.sender, _value, _data))));
> ```
> with web3 (1.0.0-beta.36) and (compiled with solidity 0.4.24)
> 
> ```
>  tokenContract.methods.transfer(receiverAddress, tokenAmount, customData, 'tokenFallback(address,uint256,bytes)').send({ from: account });
> ```
> and while I'm sure my custom contract is being called (via event logging), the `bytes _data` parameter in `function tokenFallback(address _from, uint256 _value, bytes _data) public` is still empty, `0x`.
