### ISSUE TITLE
Initialize Empty variable for _data parameter in ERC223

### ISSUE THREAD

**Issue by hskang9** [Dexaran/ERC223-token-standard#53]
### Description

_data is a parameter which acts as tx.data on ethereum transaction.

ERC223's transfer(address _to, uint256 _value) function handles two cases:

1. transfer to address

2. transfer to smart contracts with _data parameter with empty value( bytes memory empty; )

First case works fine, but second case is not executed with current declaration with bytes

```
    bytes memory empty;
```

It just returns empty(0x) due to solidity bug in #51 (more detail on [this](https://github.com/ethereum/solidity/issues/2884#issuecomment-329169020)

### To fix This
The bug is still on fix but I have a temporary solution.

I found out the transferToContract works when _data has at least 4-byte array.

Based on this, I suggest new empty variable for _data parameter with initialization:

```
bytes memory empty = hex"00000000" ;
```

**Comment by hskang9** [comment]
The token transfer worked fine, but I could not notice the problems in the assembly. I appreciate your effort @thekevinbrown.

**Comment by hskang9** [comment]
You might want to look hex keyword.

**Comment by thekevinbrown** [comment]
@hskang9 it does the same thing with the hex keyword.
