### ISSUE TITLE
transfer functions should return success

### ISSUE THREAD

**Issue by coinop-logan** [Dexaran/ERC223-token-standard#58]
Everywhere I've searched, everyone seems to be in agreement that the transfer functions should return bool success. However, the both ERC223_interface.sol and ERC223_token.sol do not return success; they revert. Is the spec wrong? Did I miss an updated spec somewhere? Or is the Solidity wrong?

**Comment by Dexaran** [comment]
Implemented: https://github.com/Dexaran/ERC223-token-standard/commit/d3af53a93e628d1b39a864b16f861e052217b789
