### ISSUE TITLE
ERC20 vs ERC223 GST2 ERC20 coin is not accepted by ERC 20 GST2 deposit address because of different chain.

### ISSUE THREAD

**Issue by lgpops** [Dexaran/ERC223-token-standard#74]
Disclaimer: Not sure if this belongs here but: I'm trying to convert a token (GST2) from ETC blockchain to ETH blockchain so that it can be accepted at an exchange. 

Is there a way to implement this.

To clarify I used Saturn network to purchase these using an ETC-GST2 pairing.

**Comment by Dexaran** [comment]
You'd better contact Saturn Network developers.

**Comment by Dexaran** [comment]
The token standard only describes what "default" function a token is obligated to have and what the names of the functions should look like. This is necessary to enable third-party developers know that if a token supports ERC223 standard then it certainly has a transfer function and it is called exactly "transfer" (not "send" , "deliver", "makeTransaction" or something else).

The token standard has nothing to do with the logic of cross-chain swaps nor the logic of the exchange.

**Comment by lgpops** [comment]
Thanks, they're trying to get it back online, but I fear by then it will be too late.
