### ISSUE TITLE
Implementation is missing `transferFrom` function (so ERC223 is not a superset of ERC20).

### ISSUE THREAD

**Issue by lukehutch** [Dexaran/ERC223-token-standard#80]
Both `ERC223.sol` and `IERC223.sol` are missing the `allowance`, `approve`, and `transferFrom` functions [required](https://github.com/Dexaran/ERC223-token-standard/blob/development/token/ERC223/IERC223.sol) by ERC-20; therefore, ERC223 is not a superset of ERC20.

https://github.com/Dexaran/ERC223-token-standard/blob/development/token/ERC223/IERC223.sol
https://github.com/Dexaran/ERC223-token-standard/blob/development/token/ERC223/ERC223.sol

**Comment by nitishpatel** [comment]
I was working on this, and have created a Hardhat Project to implement the same https://github.com/nitishpatel/erc223

**Comment by Dexaran** [comment]
`allowance` / `approve`  and `transferFrom` are insecure and deprecated patterns that were required to address a call stack depth flaw of the old VM. Now they are irrelevant.

So I don't see any reason to require them in a basic implementation of the standard. You can add them if you really want but they are useful for nothing if the communication model is supported in a standard.

And the communication model is supported in ERC-223.
