### ISSUE TITLE
Sending to ERC223 recipient succeeds by calling fallback function even if `IERC223Recipient.tokenReceived` is not defined

### ISSUE THREAD

**Issue by lukehutch** [Dexaran/ERC223-token-standard#81]
Sending to an ERC223 recipient succeeds by calling the fallback function even if `IERC223Recipient.tokenReceived` is not defined. (The fallback function is called whenever a function call can't find the function in a contract). Since `IERC223Recipient.tokenReceived` is not expected to return anything, there is no way for the caller to to know that the fallback function has been called (if it is defined), rather than `IERC223Recipient.tokenReceived`.

Since the fallback function is quite often defined for smart contracts, this will lead to tokens potentially being sent to smart contracts that don't know how to handle them -- thus ERC223 fails at its primary objective.

Please see ERC1363 or ERC4524 for how to properly fix this -- the recipient interface function should return a magic value (its function selector) that indicates that the function called is the intended one. Alternatively ERC1820 can be used to register a supported interface for the receiver, as for ERC777.

**Comment by Dexaran** [comment]
I have implemented the "magical value return" in the reference implementation. However it is questionable if it must be part of the standard. If you implement a permissive fallback function in the contract - you may want to accept ANYTHING. So there must be a way to do so.
